gridflow:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: staging
      location: "{{ env_var('BQ_LOCATION', 'EU') }}"
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      threads: 4
      priority: interactive
      maximum_bytes_billed: 1000000000